# Generated by Django 3.2.6 on 2024-01-16 13:26

import core.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='competitiontype',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='competitiontypes',
            field=models.SmallIntegerField(choices=[(1, 'Brazo1'), (2, 'Brazo2'), (3, 'Brazo3'), (4, 'Brazo4'), (5, 'Brazo5')], null=True, verbose_name='Competencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='rut',
            field=core.custom_fields.RutField(max_length=10, null=True, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.CharField(max_length=50, null=True, verbose_name='Tiempo'),
        ),
    ]
