# Generated by Django 3.2.6 on 2024-01-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240116_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionType',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
