# Generated by Django 3.2.6 on 2024-01-17 01:09

import core.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Alumno')),
                ('rut', core.custom_fields.RutField(max_length=10, null=True, unique=True, verbose_name='Rut')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('time', models.CharField(max_length=50, null=True, verbose_name='Tiempo')),
                ('competitiontypes', models.SmallIntegerField(choices=[(1, 'Brazo1'), (2, 'Brazo2'), (3, 'Brazo3'), (4, 'Brazo4'), (5, 'Brazo5')], null=True, verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
